---
title: 'SA: The Song of Achilles'
author: "Mark Baber"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Using Sentiment Analysis on the book 'The Song of Achilles'.

This is a good book.

Import the libraries.

```{r import-libraries}
library(tidytext)
library(textdata)
library(dplyr)
library(stringr)
library(readr)
library(janeaustenr)
library(tidyr)
library(ggplot2)
```

Next import the Data

```{r import-data}
# import the book
df <- read_csv("the-song-of-achilles.txt")
```

```{r}
# mutate and get the chapter
df_tidy <- df %>% mutate(
  linenumber = row_number(),
  chapter = cumsum(str_detect(text,
                              regex("^chapter [\\divxlc]", 
                                    ignore_case = TRUE)))) %>% 
  ungroup() %>%
  unnest_tokens(word, text)
```


```{r}
# remove stop words
df_tidy <- df_tidy %>% 
  anti_join(stop_words)
```


```{r}
# check against nrc
nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")
```


```{r}
# Get the joy sentiment word
df_tidy %>%
  inner_join(nrc_joy) %>%
  count(word, sort = TRUE)
```


```{r}
# Join bind lexicon to the tidied df
# with positive and negative.
soa <- df_tidy %>%
  inner_join(get_sentiments("bing")) %>%
  count(index = linenumber %/% 80, sentiment) %>%
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>% 
  mutate(sentiment = positive - negative)
```


```{r}
# Make a plot of the positive vs negative
ggplot(soa, aes(index, sentiment, fill = sentiment)) +
  geom_col(show.legend = F) +
  labs(
    x = "Index",
    y = "Sentiment",
    title = "Sentiment Analysis | bing",
    subtitle = "Book: The Song of Achilles"
  )
# No wonder I cried..
```


```{r}
# Compare the lexicons for the book: afinn, bind, nrc
afinn <- df_tidy %>% 
  inner_join(get_sentiments("afinn")) %>% 
  group_by(index = linenumber %/% 80) %>% 
  summarise(sentiment = sum(value)) %>% 
  mutate(method = "AFINN")

bing_and_nrc <- bind_rows(
  df_tidy %>% 
    inner_join(get_sentiments("bing")) %>%
    mutate(method = "Bing et al."),
  df_tidy %>% 
    inner_join(get_sentiments("nrc") %>% 
                 filter(sentiment %in% c("positive", 
                                         "negative"))
    ) %>%
    mutate(method = "NRC")) %>%
  count(method, index = linenumber %/% 80, sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0) %>% 
  mutate(sentiment = positive - negative)
```


```{r}
# bind and plot
bind_rows(afinn, 
bing_and_nrc) %>%
  ggplot(aes(index, sentiment, fill = method)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~method, ncol = 1, scales = "free_y") +
  labs(
    x = "Index",
    y = "Sentiment",
    title = "Sentiment Analysis",
    subtitle = "Book: The Song of Achilles"
  )
```


```{r}
# get positive vs negative
bing_word_counts <- df_tidy %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()
```


```{r}
# plot the differences
bing_word_counts %>%
  group_by(sentiment) %>%
  slice_max(n, n = 15) %>% 
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL)
```


```{r}
# Wordcloud
library(wordcloud)
# create a word cloud without the stop words
df_tidy %>%
  anti_join(stop_words) %>%
  count(word) %>%
  with(wordcloud(word, n, max.words = 100))
```


```{r}

library(reshape2)
df_tidy %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("gray20", "gray80"),
                   max.words = 100)

```

